select * from customer limit 20;

-- Q1. What is the total revenue generated by male vs female customers ?
select gender,sum(purchase_amount) 
from customer 
group by gender;


-- Q2.Which customer used a discount but still spent more than average purchase_amount ?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and 'yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );


-- Q3. Which are the top 5 Products with the highest average review rating 

select item_purchased, avg(review_rating)
from customer
group by item_purchased
order by avg(review_rating) DESC
limit 5;

select item_purchased,ROUND(avg(review_rating::numeric),2)
from customer
group by item_purchased
order by avg(review_rating) DESC
limit 5;


--Q4. Compare the average Purchase Amount between Standard and Express Shipping.

Select shipping_type,
Round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5.Do subscribed customers spend more ? Comapare average spend and total revenue 
-- between subscribers and non-subcribers

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;


-- Q6. Which 5 Products have the highest percentage of purchases with discounts applied
SELECT item_purchased,
SUM(CASE  WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 10;

-- Q7. Segment customers into new, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT
        CASE
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS "Number of Customer"
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count (customer_id) DESC)as item_rank
from customer 
group by category, item_purchased)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group ?
SELECT
    "Age_group",
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 /
        SUM(SUM(purchase_amount)) OVER (),
        2
    ) AS revenue_contribution
FROM customer
GROUP BY "Age_group"
ORDER BY revenue_contribution DESC;

